on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    # Use macOS here to speed up by binary R package install (and Windows may have more issues, such as Rtools)
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install MacOS system dependencies
        # We are on macOS as per the "runs-on":
        #if: runner.os == 'macOS'
        run: |
          # gfortran may not exist in a period after a new R minor release:
          gfortranFile='/usr/local/bin/gfortran'
          if [ -f "$gfortranFile" ] ; then
            rm "$gfortranFile"
          fi
          rm -f '/usr/local/bin/2to3'
          rm -f '/usr/local/bin/2to3-3.11'
          rm -f '/usr/local/bin/idle3'
          rm -f '/usr/local/bin/idle3.11'
          rm -f '/usr/local/bin/pydoc3'
          rm -f '/usr/local/bin/pydoc3.11'
          rm -f '/usr/local/bin/python3'
          rm -f '/usr/local/bin/python3.11'
          rm -f '/usr/local/bin/python3-config'
          rm -f '/usr/local/bin/python3.11-config'
          rm -f '/usr/local/bin/gfortran'
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK= # This (the value should actually be empty...) prevents Homebrew from re-installing R, which will lead to .Platform$pkgType = "source".
          brew install gdal
        shell: bash

      - name: Install R package dependencies
        run: |
          # We hard code the list of top level dependencies, since the behavior of remotes::install_deps() that we used before is very unclear (e.g. how is the Additional_repositories included in the list of repos?):
          topLevelDeps <- c(
            # Imports: 
            "data.table",
            "ggplot2",
            "gridExtra",
            "methods",
            "RColorBrewer",
            "rnaturalearth",
            "rnaturalearthdata",
            "RstoxData",
            "RstoxBase",
            "sf",
            # Suggests: 
            "knitr",
            "rmarkdown",
            "tinytest"
          )
          install.packages(
            topLevelDeps, 
            dependencies = TRUE, 
            repos = c("https://stoxproject.github.io/unstableRepo/", "https://cloud.r-project.org/")
          )
          
          # Used in "Deploy package" below:
          install.packages("pkgdown", type = "binary")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
